/**
 * Agent Native Relay Server
 *
 * Routes WebSocket messages between:
 *   - OpenClaw Connector (server-side) connects with role=connector&token=xxx
 *   - Mobile App (client-side) connects with role=device&token=xxx
 *
 * For each token, maintains a pair of connections and forwards messages between them.
 */

const { WebSocketServer, WebSocket } = require("ws");
const http = require("http");
const url = require("url");
const crypto = require("crypto");

const PORT = parseInt(process.env.PORT || "8787");

// Token → { connector: ws, device: ws }
const rooms = new Map();

// Pending tokens (generated by relay, waiting for connector)
const pendingTokens = new Map(); // token → { createdAt, deviceWs? }

const server = http.createServer((req, res) => {
  const parsed = url.parse(req.url, true);

  // Serve install script
  if (parsed.pathname === "/install.sh") {
    const fs = require("fs");
    const path = require("path");
    const script = fs.readFileSync(path.join(__dirname, "connector", "install.sh"), "utf-8");
    res.writeHead(200, { "Content-Type": "text/plain" });
    res.end(script);
    return;
  }

  // Health check
  if (parsed.pathname === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ ok: true, rooms: rooms.size, pending: pendingTokens.size }));
    return;
  }

  // Generate a new pairing token (called by mobile app before WS connect)
  if (parsed.pathname === "/pair/new" && req.method === "POST") {
    const token = crypto.randomBytes(16).toString("hex");
    pendingTokens.set(token, { createdAt: Date.now() });
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ token }));
    return;
  }

  // Check pairing status
  if (parsed.pathname === "/pair/status") {
    const token = parsed.query.token;
    if (!token) {
      res.writeHead(400);
      res.end("missing token");
      return;
    }
    const room = rooms.get(token);
    const connected =
      room &&
      room.connector &&
      room.connector.readyState === WebSocket.OPEN &&
      room.device &&
      room.device.readyState === WebSocket.OPEN;
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(
      JSON.stringify({
        token,
        connectorOnline: !!(room?.connector?.readyState === WebSocket.OPEN),
        deviceOnline: !!(room?.device?.readyState === WebSocket.OPEN),
        paired: !!connected,
      })
    );
    return;
  }

  res.writeHead(404);
  res.end("not found");
});

const wss = new WebSocketServer({ server });

wss.on("connection", (ws, req) => {
  const parsed = url.parse(req.url, true);
  const token = parsed.query.token;
  const role = parsed.query.role; // 'connector' or 'device'

  if (!token || !role || !["connector", "device"].includes(role)) {
    ws.close(4000, "missing token or role");
    return;
  }

  console.log(`[${role}] connected with token ${token.slice(0, 8)}...`);

  // Get or create room
  if (!rooms.has(token)) {
    rooms.set(token, { connector: null, device: null });
  }
  const room = rooms.get(token);

  // Close existing connection for this role if any
  if (room[role] && room[role].readyState === WebSocket.OPEN) {
    room[role].close(4001, "replaced by new connection");
  }
  room[role] = ws;

  // Notify peer that partner connected
  const peer = role === "connector" ? "device" : "connector";
  if (room[peer] && room[peer].readyState === WebSocket.OPEN) {
    room[peer].send(
      JSON.stringify({ type: "relay.peer_connected", role })
    );
    ws.send(JSON.stringify({ type: "relay.peer_connected", role: peer }));
    console.log(`[relay] token ${token.slice(0, 8)}... paired!`);
  }

  // Forward messages to peer
  ws.on("message", (data) => {
    const peerWs = room[peer];
    if (peerWs && peerWs.readyState === WebSocket.OPEN) {
      peerWs.send(data);
    }
  });

  ws.on("close", () => {
    console.log(`[${role}] disconnected, token ${token.slice(0, 8)}...`);
    if (room[role] === ws) {
      room[role] = null;
    }
    // Notify peer
    const peerWs = room[peer];
    if (peerWs && peerWs.readyState === WebSocket.OPEN) {
      peerWs.send(
        JSON.stringify({ type: "relay.peer_disconnected", role })
      );
    }
    // Clean up empty rooms
    if (!room.connector && !room.device) {
      rooms.delete(token);
    }
  });

  ws.on("error", (err) => {
    console.error(`[${role}] error:`, err.message);
  });
});

// Clean up stale pending tokens every 5 minutes
setInterval(() => {
  const now = Date.now();
  for (const [token, info] of pendingTokens) {
    if (now - info.createdAt > 30 * 60 * 1000) {
      pendingTokens.delete(token);
    }
  }
}, 5 * 60 * 1000);

server.listen(PORT, () => {
  console.log(`Agent Native Relay listening on :${PORT}`);
});
